name: Build Image (VYOS)

on:
  workflow_call:
    inputs:
      debian_mirror:
        required: true
        type: string
        default: 'http://deb.debian.org/debian/'
      debian_security_mirror:
        required: true
        type: string
        default: ''
      vyos_mirror:
        required: true
        type: string
        default: 'https://packages.vyos.net/repositories/'
      branch:
        required: true
        type: string
        default: current
      arch:
        required: false
        type: string
        default: amd64
      build_by:
        required: true
        type: string
        default: 'autobuild@vyos.net'
      release_version:
        required: true
        type: string
        default: ''
      release_flavor:
        required: true
        type: string
        default: 'generic'
    secrets:
      token:
        required: true

env:
  BUILD_BY: ${{ inputs.build_by }}
  DEBIAN_MIRROR: ${{ inputs.debian_mirror }}
  VYOS_MIRROR: ${{ inputs.vyos_mirror }}/${{ inputs.branch }}/
  VYOS_MIRROR_APT_KEY: https://packages.vyos.net/vyos_dev_public.key
  LOCAL_GPG_KEY_PATH: /etc/apt/trusted.gpg.d/vyos_dev.gpg
  RELEASE_FLAVOR: ${{ inputs.release_flavor }}
  RELEASE_VERSION: ${{ inputs.release_version }}

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:${{ inputs.branch }}
      options: --workdir /vyos --privileged

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        repository: vyos/vyos-build  # Use public repo
        ref: ${{ inputs.branch }}

    - name: Mark directory as safe
      run: |
        set -eux
        git config --global --add safe.directory '*'

    - name: Setup env variables
      run: |
        set -eux
        echo "BUILD_VERSION=${{ env.RELEASE_VERSION }}-${{ inputs.branch }}-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Get apt key
      run: |
        set -eux
        wget ${{ env.VYOS_MIRROR_APT_KEY }}
        mv vyos_dev_public.key ${{ env.LOCAL_GPG_KEY_PATH }}

    - name: Build ISO
      run: |
        set -eux
        git remote -v
        ./build-vyos-image \
          --build-by ${{ env.BUILD_BY }} \
          --build-type release \
          --version $BUILD_VERSION \
          --vyos-mirror ${{ env.VYOS_MIRROR }} \
          --custom-apt-key ${{ env.LOCAL_GPG_KEY_PATH }} \
          ${{ env.RELEASE_FLAVOR }}
        ls -la build/

    - name: "Building: copy a ${{ env.RELEASE_FLAVOR }} ISO image"
      if: ${{ !inputs.FAKE_BUILDING_PROCESS }}
      id: copy_iso
      run: |
        set -eux
        cp ./build/live-image-${{ inputs.arch }}.hybrid.iso ./vyos-$BUILD_VERSION-${{ inputs.arch }}.iso

    - name: "Uploading artifacts: ISO image to GitHub"
      id: upload_iso_artifact
      uses: actions/upload-artifact@v4
      with:
        name: vyos-${{ env.BUILD_VERSION }}-${{ inputs.arch }}.iso
        path: ./vyos-${{ env.BUILD_VERSION }}-${{ inputs.arch }}.iso
        retention-days: 10
        if-no-files-found: error