name: Build Image (VYOS)

on:
  workflow_call:
    inputs:
      debian_mirror_url:
        required: false
        type: string
        default: 'http://deb.debian.org/debian/'
      debian_security_mirror_url:
        required: false
        type: string
        default: ''
      vyos_mirror_base_url:
        required: false
        type: string
        default: 'https://packages.vyos.net/repositories'
      arch:
        required: false
        type: string
        default: amd64
      build_by:
        required: false
        type: string
        default: 'autobuild@vyos.net'
      release_version:
        required: true
        type: string
        default: ''
      release_flavor:
        required: false
        type: string
        default: 'generic'
    secrets:
      token:
        required: false

env:
  BUILD_BY: ${{ inputs.build_by }}
  DEBIAN_MIRROR: ${{ inputs.debian_mirror_url }}
  VYOS_MIRROR_APT_KEY: https://packages.vyos.net/vyos_dev_public.key
  LOCAL_GPG_KEY_PATH: /etc/apt/trusted.gpg.d/vyos_dev.gpg
  RELEASE_FLAVOR: ${{ inputs.release_flavor }}
  RELEASE_VERSION: ${{ inputs.release_version }}

jobs:
  prepare-inputs:
    runs-on: ubuntu-latest
    outputs:
      build_branch: ${{ steps.set_branch.outputs.build_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set vyos-build branch based on version
        id: set_branch
        run: |
          version="${{ inputs.release_version }}"
          if [[ "$version" =~ ^1\.3\..* ]]; then
            echo "build_branch=equuleus" >> $GITHUB_OUTPUT
          elif [[ "$version" =~ ^1\.4\..* ]]; then
            echo "build_branch=sagitta" >> $GITHUB_OUTPUT
          elif [[ "$version" =~ ^1\.5\..* ]]; then
            echo "build_branch=circinus" >> $GITHUB_OUTPUT
          else
            echo "ERROR - Unsupported version number $version" >&2
            exit 1
          fi

  build-image:
    needs: prepare-inputs
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:current
      options: --workdir /vyos --privileged
    env:
      BUILD_BRANCH: ${{ needs.prepare-inputs.outputs.build_branch }}
      VYOS_MIRROR: ${{ inputs.vyos_mirror_base_url }}/${{ needs.prepare-inputs.outputs.build_branch }}/
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        repository: vyos/vyos-build  # Use public repo
        ref: ${{ env.BUILD_BRANCH }}

    - name: Show data dir
      run: |
        ls -lt data/build-flavors

    - name: Mark directory as safe
      run: |
        set -eux
        git config --global --add safe.directory '*'

    - name: Setup env variables
      run: |
        set -eux
        echo "BUILD_VERSION=${{ env.RELEASE_VERSION }}-${{ env.BUILD_BRANCH }}-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Get apt key
      run: |
        set -eux
        wget ${{ env.VYOS_MIRROR_APT_KEY }}
        mv vyos_dev_public.key ${{ env.LOCAL_GPG_KEY_PATH }}

    - name: Build
      run: |
        set -eux
        git remote -v
        ./build-vyos-image \
          --build-by ${{ env.BUILD_BY }} \
          --build-type release \
          --version $BUILD_VERSION \
          --vyos-mirror ${{ env.VYOS_MIRROR }} \
          --custom-apt-key ${{ env.LOCAL_GPG_KEY_PATH }} \
          ${{ env.RELEASE_FLAVOR }}
        ls -la build/